apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
      containers:
        - name: web
          securityContext:
            capabilities:
              drop:
                - all
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          image: CONTAINER_IMAGE_NAME
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: API_URL
              value: "http://api:5001"
          resources:
            requests:
              cpu: 60m
              memory: 47Mi
            limits:
              cpu: 120m
              memory: 160Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
          livenessProbe:
            tcpSocket:
              port: 8080
      nodeSelector:
        kubernetes.io/os: linux