apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app.kubernetes.io/name: web