name: api-ci
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
    tags:
      - v*
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd api/src
          # FIXME
      - name: Build container
        run: |
          cd api/src
          docker build --tag 'docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }}' .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Run container
        run: |
          docker run -d -p 8080:8080 --read-only --cap-drop=ALL --user=1000 'docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }}'
      - name: Installing KinD Cluster
        uses: engineerd/setup-kind@v0.5.0
      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl get nodes
      - name: Load image on the nodes of the cluster
        run: |
          kind load docker-image 'docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }}' --name=kind 
      - name: Deploy Kubernetes manifest
        run: |
          cd api/kubernetes
          sed -i "s,CONTAINER_IMAGE_NAME,docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }},g" deployment.yaml
          kubectl apply -f deployment.yaml
          sleep 15
          kubectl get all
          status=$(kubectl get pods -l app.kubernetes.io/name=api -o 'jsonpath={.items[0].status.phase}')
          if [ $status != 'Running' ]; then echo "Pod not running!" 1>&2; fi
      - name: Log into container registry
        if: ${{ github.event_name == 'push' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image in container registry
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push 'docker.pkg.github.com/${{ github.repository }}/api:${{ github.sha }}'