name: web-ci
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
    tags:
      - v*
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment variables
        run: |
          shortSha=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "IMAGE_NAME=docker.pkg.github.com/${{ github.repository }}/web:$shortSha" >> $GITHUB_ENV
      - name: Build container
        run: |
          cd web/src
          docker build --tag ${IMAGE_NAME} .
      - name: Log into container registry
        if: ${{ github.event_name == 'push' }}
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.CONTAINER_REGISTRY_PUSH_PRIVATE_KEY }}
          gcloud auth configure-docker
      - name: Push image in container registry
        if: ${{ github.event_name == 'push' }}
        run: docker push ${IMAGE_NAME}
          