name: web-ci
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
    tags:
      - v*
  pull_request:
jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd web/src
          docker build . --file Dockerfile
  # Push image to GitHub Packages.
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          cd web/src
          docker build . --file Dockerfile --tag 'docker.pkg.github.com/${{ github.repository }}/web:${{ github.sha }}'
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.pkg.github.com/${{ github.repository }}/web:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Log into container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image in container registry
        run: |
          docker push 'docker.pkg.github.com/${{ github.repository }}/web:${{ github.sha }}'
  # Run the container for a smoke test
  run:
    needs: push
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/${{ github.repository }}/web:${{ github.sha }}
      ports:
        - 8080
    steps:
      - name: simple task
        run: echo $ENV